kind: Service
apiVersion: v1
metadata:
    name: nginx-service
    labels:
      app: nginx-deploy
spec:
    type: NodePort
    selector: 
      app: nginx-deploy
    ports:
        - nodePort: 30002
          port: 8080
          targetPort: 80
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-store
  labels:
    app: nginx-deploy
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/cloud_user/indexdoc"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  labels:
    app: nginx-deploy
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-deploy
spec:
  selector:
    matchLabels:
      app: nginx-deploy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx-deploy
    spec:
      containers:
          - name: nginx-cont
            image: nginx
            ports:
            - containerPort: 80
            volumeMounts:
            - name: nginx-vol
              mountPath: "/usr/share/nginx/html"
      volumes:
      - name: nginx-vol
        persistentVolumeClaim:
          claimName: nginx-pvc
